### ISSUE TITLE
Firebase Storage cannot display uploaded images

### ISSUE THREAD

**Issue by plumsirawit** [Feeding-Thailand/thaifoodbank#12]
Firebase storage cannot display uploaded images. The images are uploaded in base64 format from functions. However, manually uploaded images are still possible to be displayed. Need further investigation.

**Comment by porames** [comment]
fixed. stupid bug.

**Comment by plumsirawit** [comment]
not fixed yet. need further investigation.

**Comment by plumsirawit** [comment]
done
