### ISSUE TITLE
Request for UI

### ISSUE THREAD

**Issue by plumsirawit** [Feeding-Thailand/thaifoodbank#42]
After the acceptor posted, there will be a button for contact which requires reCAPTCHA. And after reCAPTCHA, the donor will see contact details with a button to confirm to donate (which will add them to donors list using the `/donate/:id` API upon auth later).

Acceptors, at any time after posted a post, can choose to

1. Close the request (which means they are satisfied with the donors' donation)
2. Delete the request (which means they aren't satisfied, or changed their mind about their requests)

_The following features are not yet implemented and requires further discussions_

3. Remove some of the donors from their list (to be discussed and implemented later)
4. Lock the request (deny all late donors who wants to donate after the lock, to be discussed and implemented later)

**Comment by plumsirawit** [comment]
Also, there should be some kind of counter from stats or hall of fame for donors, this depends on your choice of design. Thank you.

**Comment by porames** [comment]
1. and 2. will be done, boss.
