### ISSUE TITLE
Donation canceling

### ISSUE THREAD

**Issue by plumsirawit** [Feeding-Thailand/thaifoodbank#73]
Donors should be able to revoke their donation, while acceptors should not be able to kick any donor.

@plumsirawit > write a function to cancel a transaction: `DELETE /donate/:id/cancel`
@porames > work on UI to support this (please also optimize UX to focus for normal/non-dev people)

**Comment by porames** [comment]
ok dokey.

**Comment by porames** [comment]
hey, boss. What is the `:id`? Is it the post's reference id or donor's reference id? The function seems to return 404 when I request for `DELETE donate` with the post's id.
